services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    expose:
      - "8000"
    env_file:
      - .env
    volumes:
      - ./staticfiles:/app/staticfiles
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  caddy:
    image: caddy:latest
    ports:
      - "8000:80"
      - "8080:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./staticfiles:/www/html
    depends_on:
      django:
        condition: service_started
      db:
        condition: service_healthy
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    depends_on:
      - django

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  db-data:
  grafana-data:
