global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:
  alertmanagers: []

scrape_configs:
  - job_name: 'django'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['django:8000']
        labels:
          group: 'server'
